library(dplyr)
library(ggmap)
library(timeDate)
library(shiny)
library(shinythemes)

load("uber.Rdata")
load("citiride.Rdata")
load("uberride.Rdata")
load("ridership.Rdata")
load("test.Rdata")
load("sample.Rdata")
